### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by goloveychuk** [morlay/typescript-plugin-lodash#1]
Hey, could you add a license that I could use & contribute your library to?

**Comment by morlay** [comment]
The license is [WTFPL](http://www.wtfpl.net/) 😄 

Btw, since webpack 4.0 provided `sideEffects` option, `lodash` can be partially imported easier. 
I already removed this pkg from my projects.

If you glad to continue using or maintaining this repo, I could transform it and its npm package to you.

**Comment by goloveychuk** [comment]
@morlay ok, great, thanks. I also think tree shaking is better option (since it's general). 
And sideEffects is good news.
What is your experience, did having webpack's tree shaking enabled broken anything in your project?

**Comment by morlay** [comment]
Nope. Webpack works well for us.

**Comment by goloveychuk** [comment]
ok, thanks
